package com.app.docflow.tools;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;

public final class DocumentGeneratorCli {

    private static final String USAGE_MESSAGE = "Usage: DocumentGeneratorCli <params.properties>";
    private static final String GENERATOR_HINT_CONTEXT_PATH = "Hint: check baseUrl in properties. For local profile use http://localhost:8080/docflow-service";
    private static final String PROP_N = "n";
    private static final String PROP_BASE_URL = "baseUrl";
    private static final String PROP_AUTHOR = "author";
    private static final String DEFAULT_BASE_URL = "http://localhost:8080/docflow-service";
    private static final String DEFAULT_AUTHOR = "generator";
    private static final String DOCUMENTS_API_PATH = "/api/v1/documents";
    private static final String CONTENT_TYPE_HEADER = "Content-Type";
    private static final String CONTENT_TYPE_JSON = "application/json";
    private static final String TITLE_FIELD = "title";
    private static final String AUTHOR_FIELD = "author";
    private static final String CONTENT_FIELD = "content";
    private static final String GENERATED_TITLE_PREFIX = "Generated document #";
    private static final String GENERATED_CONTENT = "Generated by utility";
    private static final int HTTP_ERROR_STATUS_THRESHOLD = 300;
    private static final int PROGRESS_PARTS = 10;
    private static final Duration HTTP_TIMEOUT = Duration.ofSeconds(10);

    private DocumentGeneratorCli() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            throw new IllegalArgumentException(USAGE_MESSAGE);
        }

        Properties props = new Properties();

        try (InputStream in = Files.newInputStream(Path.of(args[0]))) {
            props.load(in);
        }

        int n = Integer.parseInt(props.getProperty(PROP_N));
        String baseUrl = normalizeBaseUrl(props.getProperty(PROP_BASE_URL, DEFAULT_BASE_URL));
        String author = props.getProperty(PROP_AUTHOR, DEFAULT_AUTHOR);
        HttpClient client = HttpClient.newBuilder().connectTimeout(HTTP_TIMEOUT).build();
        ObjectMapper mapper = new ObjectMapper();

        long started = System.currentTimeMillis();

        System.out.println("Generator: creating N=" + n + " documents");

        for (int i = 1; i <= n; i++) {
            Map<String, Object> payload = new LinkedHashMap<>();
            payload.put(TITLE_FIELD, GENERATED_TITLE_PREFIX + i);
            payload.put(AUTHOR_FIELD, author);
            payload.put(CONTENT_FIELD, GENERATED_CONTENT);
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(baseUrl + DOCUMENTS_API_PATH))
                    .timeout(HTTP_TIMEOUT)
                    .header(CONTENT_TYPE_HEADER, CONTENT_TYPE_JSON)
                    .POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(payload)))
                    .build();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() >= HTTP_ERROR_STATUS_THRESHOLD) {
                if (response.statusCode() == 404) {
                    System.err.println(GENERATOR_HINT_CONTEXT_PATH);
                    System.err.println("Request URL: " + baseUrl + DOCUMENTS_API_PATH);
                }
                throw new IllegalStateException("Create failed at i=" + i + ", status=" + response.statusCode() + ", body=" + response.body());
            }

            if (i == 1 || i == n || i % Math.max(1, n / PROGRESS_PARTS) == 0) {
                System.out.println("Progress: " + i + "/" + n);
            }
        }

        System.out.println("Generator done in ms=" + (System.currentTimeMillis() - started));
    }

    private static String normalizeBaseUrl(String baseUrl) {
        if (baseUrl == null) {
            return DEFAULT_BASE_URL;
        }
        String trimmed = baseUrl.trim();
        if (trimmed.endsWith("/")) {
            return trimmed.substring(0, trimmed.length() - 1);
        }
        return trimmed;
    }

}
